# Generated by Django 2.2 on 2019-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEmailInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Email Interest',
                'verbose_name_plural': 'Email Interests',
            },
        ),
    ]
