# Generated by Django 2.2 on 2019-07-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_failedemailinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failedemailinterest',
            options={'verbose_name': 'Failed Email Interest', 'verbose_name_plural': 'Failed Email Interests'},
        ),
    ]
