# Generated by Django 2.2 on 2019-07-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190724_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FailedEmailInterest',
        ),
    ]
