# Generated by Django 2.1.4 on 2019-03-15 22:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Company ID',
                'verbose_name_plural': 'Company IDs',
            },
        ),
        migrations.CreateModel(
            name='MetricEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(max_length=300, verbose_name='Company')),
                ('department', models.CharField(max_length=300, verbose_name='Department')),
                ('account_type', models.IntegerField(verbose_name='Account Type')),
                ('date', models.CharField(max_length=11, verbose_name='Date')),
                ('time', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='Time')),
                ('timezone_abbreviation', models.CharField(max_length=100, verbose_name='Timezone')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('session_id', models.CharField(max_length=100, verbose_name='Session ID')),
                ('data', models.CharField(max_length=600, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Metric Event',
                'verbose_name_plural': 'Metric Events',
            },
        ),
        migrations.CreateModel(
            name='PermissionBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=100, verbose_name='Session ID')),
                ('encoded_email', models.CharField(blank=True, max_length=254, verbose_name='Encoded Email')),
                ('company', models.CharField(blank=True, max_length=300, verbose_name='Company')),
                ('department', models.CharField(blank=True, max_length=300, verbose_name='Department')),
                ('account_type', models.IntegerField(blank=True, null=True, verbose_name='Account Type')),
            ],
            options={
                'verbose_name': 'Permission Buffer',
                'verbose_name_plural': 'Permission Buffers',
            },
        ),
    ]
