# Generated by Django 2.2 on 2019-04-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesdk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricevent',
            name='session_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Session ID'),
        ),
    ]
