# Generated by Django 2.2 on 2019-04-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firesdk', '0002_auto_20190412_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricevent',
            name='session_id',
            field=models.CharField(default='rest', max_length=100, verbose_name='Session ID'),
            preserve_default=False,
        ),
    ]
