# Generated by Django 2.2 on 2019-04-12 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('firesdk', '0003_auto_20190412_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionbuffer',
            name='id',
        ),
        migrations.AlterField(
            model_name='permissionbuffer',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
